<a href="https://colab.research.google.com/github/bashant21/DataScienceBootcamp/blob/main/Class%20Notes/Lecture/L_AUG29_NUMPY.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
#Changing list to array
import numpy as np
lst1 =[1, 2, 3, 4, 5, True, 'Bashant']
arr1=np.array(lst1)
print(arr1)
print(type(arr1))

['1' '2' '3' '4' '5' 'True' 'Bashant']
<class 'numpy.ndarray'>


In [13]:
import numpy as np
lst1 = [11,22,33,44,55,66,77,88,99,110]
arr1 = np.array(lst1)
print(type(arr1))

<class 'numpy.ndarray'>


In [14]:
#Changing tuple to array
import numpy as np
tup1 = (1, 2, 3, 4, 5, True, False, 'Bashant')
arr2 = np.array(tup1)
print(arr2)
print(type(arr2))

['1' '2' '3' '4' '5' 'True' 'False' 'Bashant']
<class 'numpy.ndarray'>


In [15]:
tup1 = (12,23,34,45,56,67,78,89,90)
arr2 = np.array(tup1)
print(type(arr2))

<class 'numpy.ndarray'>


In [7]:
#Changing Set to array
import numpy as np
set1 = {1, 2, 3, True, False, 'Bashant'}
arr3 = np.array(set1)
print(arr3)
print(type(arr3))

{False, 1, 2, 3, 'Bashant'}
<class 'numpy.ndarray'>


In [16]:
set1 = {1,2,3,4,5,0,True,False,'Python','Programming'}
arr3 = np.array(set1)
arr3

array({0, 1, 2, 3, 4, 5, 'Programming', 'Python'}, dtype=object)

In [8]:
#Changing Dictionary to array
import numpy as np
dict1 = {'a': [1,2 ,3, 4, 5], 'b' : (True, False), 'c' : 'Python'}
arr5 = np.array(dict1)
print(arr5)
print(type(arr5))

{'a': [1, 2, 3, 4, 5], 'b': (True, False), 'c': 'Python'}
<class 'numpy.ndarray'>


In [17]:
dict1 = {'a':[1,2,3,4,5,0],'b':(True,False),'c':'Python','d':'Programming'}
arr4 = np.array(dict1)
arr4

array({'a': [1, 2, 3, 4, 5, 0], 'b': (True, False), 'c': 'Python', 'd': 'Programming'},
      dtype=object)

In [18]:
str1 = 'Python Programming'
arr5 = np.array(str1)
print(arr5)

Python Programming


In [9]:
#One dimensional array
arr1 = np.array([1,2, 3, 4,5 , 6])
print(arr1)
print(arr1.ndim)

[1 2 3 4 5 6]
1


In [19]:
arr1d = np.array([1,2,3,4,5,6,7,8,9,10])
print(arr1d)
arr1d.ndim

[ 1  2  3  4  5  6  7  8  9 10]


1

In [11]:
#Two dimensional array
arr2 = np.array([[1,2 ,3, 4, 5], [6, 7, 8, 9,10]])
print(arr2)
print(arr2.ndim)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
2


In [20]:
arr2d = np.array([[1,2,3,4,5],[9,8,7,6,5]])
print(arr2d)
arr2d.ndim

[[1 2 3 4 5]
 [9 8 7 6 5]]


2

In [12]:
#Three dimensional array
arr3 = np.array([[[1, 2, 3], [4, 5, 6]], [[11, 12, 13], [14, 15, 16]]])
print(arr3)
print(arr3.ndim)

[[[ 1  2  3]
  [ 4  5  6]]

 [[11 12 13]
  [14 15 16]]]
3


In [21]:
arr3d = np.array([[[1,2,3],[2,3,4]],[[3,4,5],[4,5,6]]])
print(arr3d)
arr3d.ndim

[[[1 2 3]
  [2 3 4]]

 [[3 4 5]
  [4 5 6]]]


3

In [22]:
a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
e = np.array([
    [[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]],
    [[[11, 12, 13], [14, 15, 16]], [[11, 12, 13], [14, 15, 16]]]
    ])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)
print(e.ndim)

0
1
2
3
4
